dist: trusty
sudo: require
language: cpp
compiler: gcc
notifications:
  email:
    on_success: always
    on_failure: always
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
script:
  - mkdir build
  - cd build
  - cmake ../
  - make

